CREATE USER [TVAUser]
	FOR LOGIN [TVALogin]
	WITH DEFAULT_SCHEMA = [dbo];
GO

GRANT CONNECT TO [TVAUser];
GO

GRANT EXECUTE ON SCHEMA::dbo TO [TVAUser];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::dbo.Persons TO [TVAUser];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::dbo.Accounts TO [TVAUser];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::dbo.Transactions TO [TVAUser];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::dbo.AccountsAudit TO [TVAUser];
GO